Valid_path: ./data/benign_100/val  # Ensure the validation dataset is consistent with training dataset
dataset: imagenet100
mark_budget: 0.1
trigger_size: 8
wm_path: ./data/Zmark/imagenet100/
alpha: 0.2
larger_num: 10
img_mean: [0.485, 0.456, 0.406]  # imagenet_mean
img_std: [0.229, 0.224, 0.225] # imagenet_std
resize: 224
num_classes: 100
num_sample: 2
original_label: 2
target_label: 0
constraint: l2
num_iterations: 80
gamma: 100.0
stepsize_search: geometric_progression
max_num_evals: 8000
init_num_evals: 80
tau: 0.02 # The cotefficient is used to run T_test
wsr: True # Whether to test watermark success rate