valid_path: ./data/cifar10-imagefolder/test
resize: 32
seed: 666
lr: 0.03
momentum: 0.9
wd: 0.001
epochs: 90
model_num: 4
batch_size: 128
query_num: 8
num_cls: 10
attack_epochs: 100
dataset_name: cifar10
model_name: resnet18