test_path: data/cifar10-imagefolder/test
num_classes: 10
batch_size: 128
lr: 0.03
momentum: 0.9
wd: 0.001
epochs: 90
resize: 32
distance: l2
dataset: cifar10
feature_type: rand # rand or mingd
alpha_l_1: 1.0
alpha_l_2: 0.01
alpha_l_inf: 0.001
k: 100
num_iter: 500
gap: 0.001
audit_method: "DI"
attack_list: ["fgsm", "pgd", "uap", "tifgsm", "vnifgsm"]
target_label: null
reverse: true
fgsm:
  epsilon: 0.03
uap:
  epsilon: 0.05
  alpha: 0.004
  max_iter: 20
pgd:
  epsilon: 0.05
  alpha: 0.004
  iters: 20
tifgsm:
  epsilon: 0.05
  alpha: 0.004
  steps: 20
vnifgsm:
  epsilon: 0.05
  alpha: 0.004
  steps: 20
black-box:
  model: MobileNetV2
  epochs: 90
  batch_size: 16
  lr: 0.01
  alpha: 0.5
  temperature: 8.0
  pre-trained-path: "model/distillation/MobileNetV2.pth"
  retrain: false