#seed
seed: 666
# data
dataset: cifar10
data_path: ./data/cifar10-imagefolder/
resize: 32
batch_size: 128
num_classes: 10
epochs: 90
attack_model_epochs: 200
attack_model_lr: 0.001
attack_model_wd: 0.0
# model related
learning_rate: 0.03
momentum: 0.9
wd: 0.001
step_size: 30
gamma: 0.1
number_shadow_model: 10
shadow_model_path: ./model/MIA/cifar10/
attack_model_path: ./model/MIA/cifar10/attack_model.pth
retrain_attack_model: False