#seed
seed: 666
# data
dataset: imagenet100
data_path: ./data/benign_100/
resize: 224
batch_size: 512
num_classes: 100
epochs: 120
attack_model_epochs: 200
attack_model_lr: 0.001
attack_model_wd: 0.0
# model related
learning_rate: 0.03
momentum: 0.9
wd: 0.01
step_size: 30
gamma: 0.1
number_shadow_model: 10
shadow_model_path: ./model/MIA/imagenet100true/
attack_model_path: ./model/MIA/imagenet100true/attack_model.pth
retrain_attack_model: False