python main.py \
    --gpus "5" \
    --epochs 60 \
    --lr 0.05 \
    --momentum 0.9 \
    --optim "sgd" \
    --bs 128 \
    --wd 1e-4 \
    --eval_rounds 10 \
    --test_bs 128 \
    --model "ResNet18" \
    --dataset "cifar10-imagefolder" \
    --image_size 32 \
    --seed 235 \
    --save_dir "./results/" \
    --save_model \
    --mode "train" \
    --audit_method "UBWC" \
    --audit_config_path "config/UBWC/cifar10-resnet18.yaml" \
    --reprocessing